{% set name = "syft-proto" %}
{% set version = "0.4.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 609464f52f3aec65f267cd63ed163a543a1233a8c52eb6ca9f6ce56e4bb1a527

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - protobuf >=3.11.1
    - python

test:
  imports:
    - syft_proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenMined/syft-proto
  summary: PySyft protocol constants.
  license: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - systemshift
