{% set name = "syft-proto" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e83580670b63d50744b219ced59b04c75fd150e9d9577c898129c820089c4024

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - protobuf >=3.11.1
    - python >={{ python_min }}

test:
  imports:
    - syft_proto
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/OpenMined/syft-proto
  summary: PySyft protocol constants.
  license: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - systemshift
