{% set name = "syft-proto" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebc8d7ed1cbfdb8e45b56c0b5578c03d6289b0d04c52e0a6a72155bd617d5406

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - protobuf >=3.11.1
    - python

test:
  imports:
    - syft_proto
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenMined/syft-proto
  summary: PySyft protocol constants.
  license: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - systemshift
